# Evaluation Results

Import packages.

In [7]:
import pandas as pd
from pathlib import Path

Specify the configuration to read results for.

In [8]:
num_models = 4
# opt_metric = "mse"
opt_metric = "mae"
num_windows = 1
ensemble = "SLSQPEnsemble"

alias = f"{ensemble}_{num_models}-models_opt-{opt_metric}_{num_windows}-windows"

Read all of the configuration's CSV files into a single DataFrame and save the aggregated results.

In [9]:
input_path = Path(f"../results/{alias}/")
csv_files = list(input_path.rglob("*.csv"))

df = pd.concat((pd.read_csv(f).tail(1) for f in csv_files), ignore_index=True)
print(f"df shape: {df.shape}")

output_path = Path(f"../results/all_results/{alias}") / "all_results.csv"
output_path.parent.mkdir(parents=True, exist_ok=True)
df.to_csv(output_path, index=False)
print(f"Saved aggregatted results to {output_path}")

df.head()

df shape: (97, 15)
Saved aggregatted results to ../results/all_results/SLSQPEnsemble_4-models_opt-mae_1-windows/all_results.csv

,dataset,model,eval_metrics/MSE[mean],eval_metrics/MSE[0.5],eval_metrics/MAE[0.5],eval_metrics/MASE[0.5],eval_metrics/MAPE[0.5],eval_metrics/sMAPE[0.5],eval_metrics/MSIS,eval_metrics/RMSE[mean],eval_metrics/NRMSE[mean],eval_metrics/ND[0.5],eval_metrics/mean_weighted_sum_quantile_loss,domain,num_variates
0,solar/H/medium,SLSQPEnsemble_4-models_opt-mae_1-windows,499.524910,499.524910,10.003362,0.762649,3.691779,1.388875,10.824734,22.350054,0.805101,0.360344,0.305832,Energy,1
1,solar/H/short,SLSQPEnsemble_4-models_opt-mae_1-windows,555.664517,555.664517,9.933452,0.764981,3.845165,1.390470,8.458380,23.572537,0.868892,0.366150,0.303744,Energy,1
2,solar/H/long,SLSQPEnsemble_4-models_opt-mae_1-windows,426.467114,426.467114,9.870362,0.750051,4.277436,1.384698,11.080526,20.651080,0.716011,0.342223,0.292837,Energy,1
3,solar/10T/medium,SLSQPEnsemble_4-models_opt-mae_1-windows,21.131595,21.131595,1.880064,0.821731,3.611351,1.457014,6.131195,4.596911,1.020073,0.417194,0.336425,Energy,1
4,solar/10T/short,SLSQPEnsemble_4-models_opt-mae_1-windows,14.267304,14.267304,1.479648,0.638728,3.628875,1.486196,4.108379,3.777209,1.098790,0.430430,0.339393,Energy,1

Display all of the results and only show the MASE and CRPS columns.

In [10]:
pd.set_option('display.max_rows', None)

df = df.rename(columns={
    "eval_metrics/MASE[0.5]": "MASE",
    "eval_metrics/mean_weighted_sum_quantile_loss": "CRPS",
},
errors="ignore",
)

keep_cols = [
    "dataset",
    "MASE",
    "CRPS",
    "domain",
    "num_variates",
]
df = df[keep_cols].sort_values(by="CRPS", ascending=False).reset_index(drop=True)
display(df)

,dataset,MASE,CRPS,domain,num_variates
0,car_parts/M/short,0.815831,0.931815,Sales,1
1,bitbrains_fast_storage/5T/long,0.912993,0.773663,Web/CloudOps,2
2,bitbrains_rnd/5T/medium,4.428266,0.642064,Web/CloudOps,2
3,bitbrains_fast_storage/5T/medium,0.999749,0.640577,Web/CloudOps,2
4,bitbrains_rnd/H/short,5.813409,0.628236,Web/CloudOps,2
5,bitbrains_rnd/5T/long,3.358888,0.626335,Web/CloudOps,2
6,bitbrains_fast_storage/H/short,1.001527,0.597941,Web/CloudOps,2
7,hierarchical_sales/D/short,0.734205,0.565562,Sales,1
8,temperature_rain/D/short,1.347399,0.564302,Nature,1
9,kdd_cup_2018/D/short,1.199428,0.376796,Nature,1
10,kdd_cup_2018/H/medium,0.841162,0.376787,Nature,1
11,kdd_cup_2018/H/long,0.775086,0.374253,Nature,1
12,bitbrains_rnd/5T/short,1.624138,0.372793,Web/CloudOps,2
13,saugeen/W/short,1.149758,0.364186,Nature,1
14,bitbrains_fast_storage/5T/short,0.654518,0.362847,Web/CloudOps,2
15,hierarchical_sales/W/short,0.722024,0.348772,Sales,1
16,kdd_cup_2018/H/short,0.798773,0.342851,Nature,1
17,solar/10T/short,0.638728,0.339393,Energy,1
18,solar/10T/medium,0.821731,0.336425,Energy,1
19,solar/10T/long,0.821997,0.328862,Energy,1
20,saugeen/D/short,2.641029,0.327795,Nature,1
21,bizitobs_l2c/H/long,0.615259,0.318616,Web/CloudOps,7
22,solar/H/medium,0.762649,0.305832,Energy,1
23,solar/H/short,0.764981,0.303744,Energy,1
24,saugeen/M/short,0.714033,0.297517,Nature,1
25,solar/H/long,0.750051,0.292837,Energy,1
26,solar/D/short,1.016018,0.289943,Energy,1
27,ett1/D/short,1.682159,0.288528,Energy,7
28,bizitobs_l2c/5T/long,0.571074,0.279806,Web/CloudOps,7
29,ett1/H/long,1.381643,0.266980,Energy,7
30,bizitobs_l2c/H/medium,0.500909,0.265723,Web/CloudOps,7
31,restaurant/D/short,0.684258,0.257527,Sales,1
32,ett1/H/medium,1.262516,0.256087,Energy,7
33,ett1/W/short,1.444407,0.240164,Energy,7
34,ett1/15T/long,1.032419,0.238577,Energy,7
35,ett1/15T/medium,1.000498,0.237312,Energy,7
36,bizitobs_l2c/5T/medium,0.493990,0.222228,Web/CloudOps,7
37,solar/W/short,1.481441,0.214555,Energy,1
38,sz_taxi/15T/medium,0.544760,0.209374,Transport,1
39,sz_taxi/15T/short,0.541707,0.200269,Transport,1
40,sz_taxi/15T/long,0.511142,0.200083,Transport,1
41,ett1/H/short,0.815105,0.182419,Energy,7
42,bizitobs_l2c/H/short,0.414877,0.179129,Web/CloudOps,7
43,ett1/15T/short,0.661880,0.152592,Energy,7
44,sz_taxi/H/short,0.559694,0.134921,Transport,1
45,m_dense/H/short,0.755511,0.123494,Transport,1
46,m4_yearly/A/short,3.370323,0.114668,Econ/Fin,1
47,m_dense/H/long,0.688223,0.113148,Transport,1
48,m_dense/H/medium,0.673711,0.112133,Transport,1
49,ett2/H/long,1.029421,0.102275,Energy,7
50,ett2/H/medium,1.024832,0.101249,Energy,7
51,ett2/D/short,1.272615,0.091488,Energy,7
52,ett2/15T/long,0.898063,0.091448,Energy,7
53,m4_monthly/M/short,0.920027,0.090240,Econ/Fin,1
54,ett2/15T/medium,0.878120,0.088697,Energy,7
55,electricity/H/long,1.071563,0.087811,Energy,1
56,ett2/W/short,0.808545,0.084770,Energy,7
57,loop_seattle/5T/long,0.853057,0.077024,Transport,1
58,electricity/15T/short,0.866050,0.076261,Energy,1
59,electricity/15T/medium,0.824595,0.075328,Energy,1
60,electricity/15T/long,0.874949,0.075326,Energy,1
61,m4_quarterly/Q/short,1.202868,0.075278,Econ/Fin,1
62,electricity/H/medium,0.979254,0.074040,Energy,1
63,loop_seattle/5T/medium,0.788889,0.071152,Transport,1
64,loop_seattle/H/medium,0.924606,0.065836,Transport,1
65,bizitobs_l2c/5T/short,0.243880,0.065359,Web/CloudOps,7
66,ett2/H/short,0.728084,0.063264,Energy,7
67,m_dense/D/short,0.661487,0.062627,Transport,1
68,ett2/15T/short,0.728235,0.062544,Energy,7
69,loop_seattle/H/long,0.888407,0.062410,Transport,1
70,electricity/H/short,0.867202,0.060920,Energy,1
71,loop_seattle/H/short,0.804842,0.057835,Transport,1
72,jena_weather/H/long,0.936824,0.055304,Nature,21
73,electricity/D/short,1.389151,0.053137,Energy,1
74,electricity/W/short,1.504034,0.052773,Energy,1
75,jena_weather/H/medium,0.813949,0.052702,Nature,21
76,bizitobs_application/10S/long,3.297559,0.052540,Web/CloudOps,2
77,bizitobs_service/10S/long,1.305549,0.051470,Web/CloudOps,2
78,hospital/M/short,0.758789,0.050679,Healthcare,1
79,jena_weather/10T/long,0.647970,0.049940,Nature,21
80,jena_weather/10T/medium,0.603623,0.047856,Nature,21
81,loop_seattle/5T/short,0.516189,0.044188,Transport,1
82,jena_weather/D/short,0.975250,0.044144,Nature,21
83,loop_seattle/D/short,0.864484,0.041926,Transport,1
84,jena_weather/H/short,0.507488,0.040678,Nature,21
85,m4_weekly/W/short,1.994861,0.036688,Econ/Fin,1
86,bizitobs_application/10S/medium,2.210175,0.032999,Web/CloudOps,2
87,covid_deaths/D/short,37.479479,0.030746,Healthcare,1
88,jena_weather/10T/short,0.281858,0.026461,Nature,21
89,bizitobs_service/10S/medium,1.041705,0.026416,Web/CloudOps,2
90,m4_daily/D/short,3.240015,0.021554,Econ/Fin,1
91,m4_hourly/H/short,0.702580,0.019268,Econ/Fin,1
92,us_births/D/short,0.334337,0.017751,Healthcare,1
93,us_births/M/short,0.638596,0.013044,Healthcare,1
94,bizitobs_service/10S/short,0.780881,0.010832,Web/CloudOps,2
95,us_births/W/short,0.895513,0.010640,Healthcare,1
96,bizitobs_application/10S/short,1.176032,0.009787,Web/CloudOps,2